console.log('login function')
console.log('log out function')
console.log('develop the search ui')
console.log('develop the search functionality')
console.log('responsive search bar')
console.log('pagination')
console.log('other logics ')
console.log('infinite scroll')
console.log('some other codes for scroll')